apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-test
  labels:
    app: stress-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-test
  template:
    metadata:
      name: container
      labels:
        app: stress-test
    spec:
      containers:
        - name: server
          image: calc-server:latest
          imagePullPolicy: Never
