apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-update
  labels:
    test: test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test-deployment
  template:
    metadata:
      name: container
      labels:
        app: test-deployment
    spec:
      containers:
        - name: container
          image: test-alpine:latest
          imagePullPolicy: Never
