apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-pod
spec:
  containers:
    - name: container-1
      image: test-alpine:latest
      imagePullPolicy: Never
      env:
        - name: NUMBER
          value: "1"
    - name: container-2
      image: test-alpine:latest
      imagePullPolicy: Never
      env:
        - name: NUMBER
          value: "2"
    - name: container-3
      image: test-alpine:latest
      imagePullPolicy: Never
      env:
        - name: NUMBER
          value: "3"
    - name: container-4
      image: test-alpine:latest
      imagePullPolicy: Never
      env:
        - name: NUMBER
          value: "4"
    - name: container-5
      image: test-alpine:latest
      imagePullPolicy: Never
      env:
        - name: NUMBER
          value: "5"
