apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment-update
  labels:
    test: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deployment-update
  template:
    metadata:
      name: container
      labels:
        app: test-deployment-update
    spec:
      containers:
        - name: deployment:1
          image: test-alpine:latest
          imagePullPolicy: Never
        - name: deployment:2
          image: test-alpine:latest
          imagePullPolicy: Never
        - name: deployment:3
          image: test-alpine:latest
          imagePullPolicy: Never
        - name: deployment:4
          image: test-alpine:latest
          imagePullPolicy: Never
        - name: deployment:5
          image: test-alpine:latest
          imagePullPolicy: Never
        - name: deployment:6
          image: test-alpine:latest
          imagePullPolicy: Never
        - name: deployment:7
          image: test-alpine:latest
          imagePullPolicy: Never
        - name: deployment:8
          image: test-alpine:latest
          imagePullPolicy: Never
        - name: deployment:9
          image: test-alpine:latest
          imagePullPolicy: Never
        - name: deployment:10
          image: test-alpine:latest
          imagePullPolicy: Never
