apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment-update
  labels:
    test: test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test-deployment-update
  template:
    metadata:
      name: container
      labels:
        app: test-deployment-update
    spec:
      containers:
        - name: container-1
          image: deployment:2
          imagePullPolicy: Never
        - name: container-2
          image: deployment:2
          imagePullPolicy: Never
        - name: container-3
          image: deployment:2
          imagePullPolicy: Never
        - name: container-4
          image: deployment:2
          imagePullPolicy: Never
        - name: container-5
          image: deployment:2
          imagePullPolicy: Never
