apiVersion: v1
kind: Service
metadata:
  labels:
    run: webtest
  name: webtest
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.234.34
  clusterIPs:
    - 10.43.234.34
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 31647
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: webtest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 192.168.122.136
