apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test-replica-set
  labels:
    test: 2-2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: test-replica-set
  template:
    metadata:
      name: container
      labels:
        app: test-replica-set
    spec:
      containers:
        - name: container-1
          image: test-alpine:latest
          imagePullPolicy: Never
        - name: container-2
          image: test-alpine:latest
          imagePullPolicy: Never
        - name: container-3
          image: test-alpine:latest
          imagePullPolicy: Never
        - name: container-4
          image: test-alpine:latest
          imagePullPolicy: Never
        - name: container-5
          image: test-alpine:latest
          imagePullPolicy: Never
