apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test-replica-set
  labels:
    test: 2-2
spec:
  replicas: 20
  selector:
    matchLabels:
      app: test-replica-set
  template:
    metadata:
      name: container
      labels:
        app: test-replica-set
    spec:
      containers:
        - name: container
          image: test-alpine:latest
          imagePullPolicy: Never
