apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-test
  labels:
    app: scale-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scale-test
  template:
    metadata:
      name: container
      labels:
        app: scale-test
    spec:
      containers:
        - name: server
          image: calc-server:latest
          imagePullPolicy: Never
          resources:
            limits:
              cpu: 100m
            requests:
              cpu: 50m
