apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test-replica-set
  labels:
    test: 2-2
spec:
  replicas: 20
  selector:
    matchLabels:
      app: test-replica-set
  template:
    metadata:
      name: container
      labels:
        app: test-replica-set
    spec:
      containers:
        - name: container-1
          image: test-alpine:latest
          imagePullPolicy: Never
          env:
            - name: NUMBER
              value: "1"
        - name: container-2
          image: test-alpine:latest
          imagePullPolicy: Never
          env:
            - name: NUMBER
              value: "2"
        - name: container-3
          image: test-alpine:latest
          imagePullPolicy: Never
          env:
            - name: NUMBER
              value: "3"
        - name: container-4
          image: test-alpine:latest
          imagePullPolicy: Never
          env:
            - name: NUMBER
              value: "4"
        - name: container-5
          image: test-alpine:latest
          imagePullPolicy: Never
          env:
            - name: NUMBER
              value: "5"
